name = "ReefModEngine"
uuid = "f4ffb74a-bba7-4ac3-ad08-f8621d7c6d1d"
authors = ["Takuya Iwanaga", "Daniel Tan", "Pedro Ribeiro de Almeida", "Ryan Heneghan"]
version = "1.6.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
CSV = "0.10"
DataFrames = "1"
JSON = "0.21.4"
Dates = "1.11.0"
DimensionalData = "0.29.1"
NetCDF = "0.11.8"
Random = "1"
Statistics = "1.10.0"
StatsBase = "0.33, 0.34"
YAXArrays = "0.5.5"
julia = "1"
